from .paths import BASE_DIR, MODEL_DIR,VISUAL,SRC_DIR,DATA_DIR,RAW_DATA_DIR,RAW_DATA,PROC_DATA_DIR


__all__ = [
    "BASE_DIR", "MODEL_DIR", "VISUAL", "SRC_DIR",
    "DATA_DIR", "RAW_DATA_DIR", "RAW_DATA", "PROC_DATA_DIR"
]